version: "3"
services:
  node:
    container_name: pms-node
    build: node/
    volumes:
      - ./node:/node
      - /node/node_modules # Remove this if you have pure JS dependencies
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run start.dev"
  db:
    container_name: pms-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/db-data
volumes:
  db-data:
