# Setting up node and postgres containers
version: "3"
services:
  # Node container
  node:
    container_name: synoptic-node
    build: node/
    volumes:
      - ./node:/node
      - /node/node_modules
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run start.dev"
    depends_on:
      - db
  # Postgres container
  db:
    container_name: synoptic-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: synoptic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # Persisting data
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d/
volumes:
  db-data:
