CREATE TABLE IF NOT EXISTS test (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS admins (
    admin_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    uid SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    location VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS currentAlerts (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS userAlerts (
    id SERIAL PRIMARY KEY,
    sent_at TIMESTAMP NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_weather (
    id INT PRIMARY KEY,
    date DATE
);